---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: blackstalin-blog
    tier: blackstalin-blog
  name: blackstalin-blog
spec:
  ports:
    - name: "8090"
      protocol: TCP
      port: 8090
  selector:
    io.kompose.service: blackstalin-blog
